apiCategories = {
    "process_memory": ["VirtualAllocEx", "VirtualAlloc", "WriteProcessMemory", "ReadProcessMemory",
                        "CreateRemoteThread", "CreateThread", "VirtualProtect", "OpenProcess",
                        "GetProcAddress", "LoadLibrary", "LoadLibraryEx", "VirtualQuery",
                        "NtUnmapViewOfSection"],
    "execution": ["CreateProcess", "ShellExecute", "ShellExecuteEx", "WinExec", "system", "ExitProcess"],
    "filesystem": ["CreateFile", "ReadFile", "WriteFile", "CloseHandle", "DeleteFile", "MoveFile",
                    "MoveFileEx", "CopyFile", "SetFileTime", "GetFileAttributes", "SetFileAttributes",
                    "FindFirstFile", "FindNextFile", "GetFullPathName", "GetTempPath", "GetTempFileName",
                    "GetDiskFreeSpace", "GetFileSize", "CreateDirectory", "RemoveDirectory", "SetFilePointer",
                    "FindClose", "GetShortPathName", "SearchPath"],
    "registry": ["RegCreateKey", "RegCreateKeyEx", "RegOpenKey", "RegOpenKeyEx", "RegSetValue",
                    "RegSetValueEx", "RegDeleteKey", "RegDeleteValue", "RegQueryValue", "RegQueryValueEx",
                    "RegEnumKey", "RegEnumValue", "RegCloseKey", "RegEnumKeyEx"],
    "privilege": ["OpenProcessToken", "AdjustTokenPrivileges", "LookupPrivilegeValue",
                    "GetTokenInformation", "SetTokenInformation", "SetFileSecurity"],
    "network": ["URLDownloadToFile", "InternetConnect", "HttpSendRequest",
                "WSASocket", "socket", "connect", "send", "recv", "bind", "listen", "accept", "getaddrinfo"],
    "clipboard_input": ["GetAsyncKeyState", "GetKeyState", "SetWindowsHookEx", "OpenClipboard",
                        "SetClipboardData", "CloseClipboard", "EmptyClipboard", "GetClipboardData"],
    "gui": ["CreateWindowEx", "DispatchMessage", "DrawText", "MessageBox", "GetDlgItem",
            "SetWindowText", "SendMessage", "BeginPaint", "EndPaint", "DefWindowProc",
            "InvalidateRect", "GetDC", "ReleaseDC", "RegisterClass", "GetClassInfo",
            "LoadCursor", "GetWindowRect", "FindWindowEx", "IsWindowVisible", "ShowWindow",
            "SetForegroundWindow", "SetWindowPos", "SetWindowLong", "GetWindowLong", "SetTimer",
            "PostQuitMessage", "PeekMessage"],
    "gdi": ["SelectObject", "SetBkMode", "CreateFontIndirect", "SetTextColor",
            "DeleteObject", "GetDeviceCaps", "CreateBrushIndirect", "SetBkColor", "FillRect"],
    "anti_analysis": ["IsDebuggerPresent", "CheckRemoteDebuggerPresent", "OutputDebugString",
                        "NtQueryInformationProcess", "QueryPerformanceCounter", "GetTickCount", "Sleep"],
    "environment": ["GetModuleFileName", "GetModuleHandle", "GetWindowsDirectory", "GetSystemDirectory",
                    "GetCommandLine", "ExpandEnvironmentStrings", "GetUserName", "GetComputerName",
                    "GetVersion", "SetEnvironmentVariable", "SetCurrentDirectory"],
    "com": ["CoCreateInstance", "CoInitialize", "CoInitializeEx", "OleInitialize", "OleUninitialize",
            "CoTaskMemAlloc", "CoTaskMemFree"],
    "ini_config": ["GetPrivateProfileString", "WritePrivateProfileString"],
    "string_util": ["lstrlen", "lstrcpy", "lstrcat", "lstrcmp", "lstrcmpi", "MultiByteToWideChar",
                    "WideCharToMultiByte", "wsprintf", "CharNext", "CharPrev"],
    "shell_ui": ["SHGetSpecialFolderLocation", "SHGetPathFromIDList", "SHBrowseForFolder",
                    "SHGetFileInfo", "SHFileOperation", "ImageList_Create", "ImageList_AddMasked",
                    "ImageList_Destroy"],
    "crypto": ["CryptAcquireContext", "CryptCreateHash", "CryptHashData", "CryptVerifySignature",
                "CertOpenSystemStore", "CertGetCertificateContextProperty"],
    "service": ["CreateService", "OpenService", "StartService", "ControlService", "ChangeServiceConfig",
                "QueryServiceStatus"]
}

notableApis = [
    "VirtualAllocEx", "WriteProcessMemory", "CreateRemoteThread",
    "URLDownloadToFile", "InternetConnect", "HttpSendRequest",
    "IsDebuggerPresent", "AdjustTokenPrivileges", "SetWindowsHookEx",
    "GetAsyncKeyState", "CreateService", "CoCreateInstance", "CryptVerifySignature",
    "ExitWindowsEx", "WaitForSingleObject", "GetExitCodeProcess"
]